declare module 'vant/lib/button'
declare module 'vant/lib/tab'
declare module 'vant/lib/tabs'
declare module 'vant/lib/pull-refresh'
declare module 'vant/lib/popup'
declare module 'vant/lib/uploader'
declare module 'vant/lib/dialog'
